import type {
  MenuCategory as Category,
  MenuProduct as Product,
} from '../../features/pos/pos.types'

export const categories: Category[] = [
  { id: 'all', name: 'All Items' },
  { id: 'burgers', name: 'Burgers' },
  { id: 'pizza', name: 'Pizza' },
  { id: 'salads', name: 'Salads' },
  { id: 'sides', name: 'Sides' },
  { id: 'drinks', name: 'Drinks' },
  { id: 'desserts', name: 'Desserts' },
]

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Classic Cheeseburger',
    description: 'Grilled beef, cheddar, house sauce',
    price: 8.5,
    categoryId: 'burgers',
    tone: 'sun',
  },
  {
    id: 'prod-2',
    name: 'Double Stack Burger',
    description: 'Two patties, smoked bacon, pickles',
    price: 11.25,
    categoryId: 'burgers',
    tone: 'clay',
  },
  {
    id: 'prod-3',
    name: 'Margherita Pizza',
    description: 'San Marzano, basil, fresh mozzarella',
    price: 12.75,
    categoryId: 'pizza',
    tone: 'orchard',
  },
  {
    id: 'prod-4',
    name: 'Pepperoni Pizza',
    description: 'Crisp pepperoni, oregano, mozzarella',
    price: 13.5,
    categoryId: 'pizza',
    tone: 'berry',
  },
  {
    id: 'prod-5',
    name: 'Garden Salad',
    description: 'Mixed greens, citrus vinaigrette',
    price: 7.25,
    categoryId: 'salads',
    tone: 'mint',
  },
  {
    id: 'prod-6',
    name: 'Cobb Salad',
    description: 'Avocado, egg, turkey, blue cheese',
    price: 9.95,
    categoryId: 'salads',
    tone: 'ocean',
  },
  {
    id: 'prod-7',
    name: 'Truffle Fries',
    description: 'Parmesan, rosemary, garlic aioli',
    price: 6.25,
    categoryId: 'sides',
    tone: 'clay',
  },
  {
    id: 'prod-8',
    name: 'Crispy Chicken Bites',
    description: 'Buttermilk fried, chipotle dip',
    price: 7.5,
    categoryId: 'sides',
    tone: 'sun',
  },
  {
    id: 'prod-9',
    name: 'Sparkling Lemonade',
    description: 'House-made, mint, citrus',
    price: 3.75,
    categoryId: 'drinks',
    tone: 'ocean',
  },
  {
    id: 'prod-10',
    name: 'Cold Brew Coffee',
    description: 'Single-origin, lightly sweetened',
    price: 4.25,
    categoryId: 'drinks',
    tone: 'berry',
  },
  {
    id: 'prod-11',
    name: 'Chocolate Lava Cake',
    description: 'Warm center, vanilla bean gelato',
    price: 6.5,
    categoryId: 'desserts',
    tone: 'orchard',
  },
  {
    id: 'prod-12',
    name: 'Vanilla Panna Cotta',
    description: 'Seasonal berries, citrus zest',
    price: 5.75,
    categoryId: 'desserts',
    tone: 'mint',
  },
 
]
