import type { CSSProperties } from 'react'

export const productEditorStyles = {
  errorText: {
    color: '#ef4444',
    fontSize: '12px',
    marginTop: '4px',
  } satisfies CSSProperties,
  footerButton: {
    padding: '10px 20px',
    borderRadius: '10px',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '700',
  } satisfies CSSProperties,
  ghostButton: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    cursor: 'pointer',
    color: '#000000',
    padding: '6px 10px',
    borderRadius: '8px',
  } satisfies CSSProperties,
  helperText: {
    fontSize: '12px',
    color: '#000000',
    marginTop: '4px',
    fontWeight: '700',
  } satisfies CSSProperties,
  input: (hasError = false): CSSProperties => ({
    width: '100%',
    padding: '8px 12px',
    border: hasError ? '1px solid #ef4444' : '1px solid #b5b5b5',
    borderRadius: '10px',
    fontSize: '14px',
    backgroundColor: 'white',
    color: '#000000',
    fontWeight: '700',
  }),
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: '700',
    color: '#000000',
    marginBottom: '6px',
  } satisfies CSSProperties,
  modalBody: {
    flex: 1,
    overflowY: 'auto',
    padding: '24px',
  } satisfies CSSProperties,
  modalErrorBanner: {
    backgroundColor: '#ffffff',
    border: '1px solid #ef4444',
    borderRadius: '10px',
    padding: '12px 16px',
    marginBottom: '24px',
    color: '#dc2626',
    fontSize: '14px',
  } satisfies CSSProperties,
  modalFooter: {
    backgroundColor: 'white',
    borderTop: '1px solid #e2e8f0',
    padding: '20px 24px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexShrink: 0,
  } satisfies CSSProperties,
  modalHeader: {
    backgroundColor: 'white',
    borderBottom: '1px solid #b5b5b5',
    padding: '20px 24px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  } satisfies CSSProperties,
  modalHeaderTitle: {
    margin: 0,
    fontSize: '24px',
    fontWeight: '600',
  } satisfies CSSProperties,
  modalShell: {
    width: 'min(1120px, 100%)',
    maxHeight: 'min(92vh, 960px)',
    backgroundColor: 'white',
    borderRadius: '12px',
    boxShadow: 'none',
    border: '1px solid #b5b5b5',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'column',
  } satisfies CSSProperties,
  overlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
  } satisfies CSSProperties,
  pillButton: {
    backgroundColor: '#ffffff',
    border: '1px solid #b5b5b5',
    borderRadius: '8px',
    padding: '6px 12px',
    fontSize: '12px',
    cursor: 'pointer',
    color: '#000000',
    fontWeight: '700',
  } satisfies CSSProperties,
  sectionTitle: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#000000',
    marginBottom: '16px',
  } satisfies CSSProperties,
} as const
